### PR TITLE
Added npm package download badge in readme

### PR DESCRIPTION
**Pull request by nishith-p-shetty**
Added npm package download badge in readme

[npm](https://www.npmjs.com/package/carrierjs)

Fixes #
Added npm package download badge in readme

## Proposed Changes

  - Added npm package download badge in readme

### CODE REVIEW

**Comment by nishith-p-shetty** [comment]
some error in your integration....

**Review by theritikchoure — APPROVED** [review]
Looks good

**Comment by theritikchoure** [comment]
A heartfelt thanks to you for your contribution to this project 🎉🎉

We are really grateful for your contribution.

Please give a ⭐ to this repository and share it as you can.

**Happy Learning 💚!!!**

**Comment by theritikchoure** [comment]
Fixes #47

**Pull request merged**
