### PR TITLE
Added animations to hero

### PR DESCRIPTION
**Pull request by Blazeleo**
Fixes #

## Proposed Changes

  - Removed existing graphics
  - Kept the text color as white
  - Added the animation

### CODE REVIEW

**Review by theritikchoure — APPROVED** [review]
Looks good

**Comment by theritikchoure** [comment]
Resolves #39

**Comment by Blazeleo** [comment]
Thanks for the opportunity, I'll be looking forward to any more PR's needed from you :)

**Comment by theritikchoure** [comment]
You can use this package, find some issues and make pull request 😅

Please share this package with your community

**Pull request merged**
