### PR TITLE
Added custom scrollbar

### PR DESCRIPTION
**Pull request by anupeshverma**
Fixes #

## Proposed Changes

  # In VS Code
ezgif-3-25820d4496

  # In Chrome Browser
ezgif-3-613866a71e

### CODE REVIEW

**Comment by anupeshverma** [comment]
Regarding issue #36 
Please accept the PR.

**Comment by devXprite** [comment]
> Fixes #
> 
> ## Proposed Changes
> # In VS Code
> ezgif-3-25820d4496 [ ezgif-3-25820d4496 ](https://user-images.githubusercontent.com/77433959/198265899-1fc7b06f-98e5-44b8-bfe4-ce84a9e7fade.gif) [ ](https://user-images.githubusercontent.com/77433959/198265899-1fc7b06f-98e5-44b8-bfe4-ce84a9e7fade.gif)
> 
> # In Chrome Browser
> ezgif-3-613866a71e [ ezgif-3-613866a71e ](https://user-images.githubusercontent.com/77433959/198265560-7af3c92e-6e75-4622-a4dd-94d17be68f4c.gif) [ ](https://user-images.githubusercontent.com/77433959/198265560-7af3c92e-6e75-4622-a4dd-94d17be68f4c.gif)

@anupeshverma That looks cool!

**Comment by devXprite** [comment]
@anupeshverma That looks cool! Great work

**Review by theritikchoure — APPROVED** [review]
Good work @anupeshverma 💚

**Comment by theritikchoure** [comment]
@anupeshverma  A heartfelt thanks to you for your contribution to this project 🎉🎉

We are really grateful for your contribution.

**Happy Learning 💚!!!**

**Comment by anupeshverma** [comment]
Thank you so much @theritikchoure ❤️❤️

**Pull request merged**
