### PR TITLE
Added contributors.html file with required specifications.

### PR DESCRIPTION
**Pull request by DarkSoul26**
Fixes #

## Proposed Changes

  - Added contributors.html file.

### CODE REVIEW

**Comment by DarkSoul26** [comment]
### **Screenshot of the change:**

image

**Comment by theritikchoure** [comment]
Replace ```Go to docs``` button text and url with ```Home``` text and url.

Refer screenshot mentioned in issue #7

**Comment by DarkSoul26** [comment]
@theritikchoure can you take a look into this now?

**Comment by DarkSoul26** [comment]
### **Screenshot of the change:**
image

**Comment by theritikchoure** [comment]
@DarkSoul26 please give a star to this repository.

**Pull request merged**
