### PR TITLE
Created Greetings.yaml file for Github Actions

### PR DESCRIPTION
**Pull request by yashjoshi-dotcom**
Added Greeting Message on every issue opened or PR raised.

Proposed Changes
The given PR adds GitHub workflow action which is triggered every time a new issue or PR is raised.

##Implementation Details

This YAML file has been implemented with the help of an external library in the GitHub Action Center.
Name: peter-evans/create-or-update-comment
GitHub Link: https://github.com/peter-evans/create-or-update-comment

##Tests
Had tried the implementation on the forked library after removing the other two action files due to their access not being present but I could not find any instance where they would interfere with each other.
Results of the Tests are presented below:

For new issue
image

For new PR
image

#8

### CODE REVIEW

**Comment by yashjoshi-dotcom** [comment]
Closed the last pull request as was trying to find some workaround regarding the permission.Lets see if it works now on merging. Do Let me know if you require any further changes and sincere apologies for closing the last pr without communicating. am still in the learning phase. Hope you understand

**Comment by theritikchoure** [comment]
It's ok @yashjoshi-dotcom

Happy Learning 💚!!!

**Comment by theritikchoure** [comment]
hey @yashjoshi-dotcom, thanks man for this github action. 

There was only problem of one command - 
``` permissions: write-all```

I have added this command, now the workflow is working as expected.

```bash
name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Greet  Contributors for Creating New Issues.
        uses: peter-evans/create-or-update-comment@v1
        if: github.event_name == 'issues'
        with:
          issue-number: ${{tojson(github.event.issue.number)}}
          body: |
            @${{ github.actor }} Thank you for taking your time and effort for your contribution, we truly value it. Happy Learning!❤️
          
      - name: Greet New Contributors for Creating New PR/Issues.
        uses: peter-evans/create-or-update-comment@v1
        if: github.event.action =='opened' && ( github.event_name == 'pull_request'  || github.event_name == 'pull_request_target')
        with:
          issue-number: ${{tojson(github.event.number)}}
          body: |
            @${{ github.actor }} Thank you for taking your time and effort for your contribution, we truly value it. Happy Learning!❤️

```

**Comment by theritikchoure** [comment]
A heartfelt thanks to you for your contribution to this project 🎉🎉

We are really grateful for your contribution.

**Happy Learning 💚!!!**

**Comment by yashjoshi-dotcom** [comment]
Pretty grateful for the opportunity.<3

**Comment by theritikchoure** [comment]
If you like this repo please give a ⭐

**Pull request merged**
